CREATE DATABASE IF NOT EXISTS crud_servlet CHARACTER SET utf8;
use crud_servlet;
CREATE TABLE IF NOT EXISTS employee (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;